### ISSUE TITLE
Doesn't compatible with multer

### ISSUE THREAD

**Issue by xueenda** [imagerjs/imager#85]
Please fix. 

The file uploaded with multer has the following json object:

{ fieldname: 'avatar_image',
  originalname: 'blob',
  name: '1897942a7e194802e27db8e71c7a0fd4',
  encoding: '7bit',
  mimetype: 'image/jpeg',
  path: '/var/folders/m8/x6wjwggd7sl4qv01sb_1r6gc0000gr/T/1897942a7e194802e27db8e71c7a0fd4',
  extension: '',
  size: 12934,
  truncated: false,
  buffer: null }

The object is different from the old express file upload.

Here is the error:
/Users/endaxue/workspace/profile/node_modules/imager/lib/imager.js:843
  return (file['type'] || file['mimetype']) || file.headers['content-type'];
                                                           ^
TypeError: Cannot read property 'content-type' of undefined
    at getFileType (/Users/endaxue/workspace/profile/node_modules/imager/lib/imager.js:843:60)
    at prepare (/Users/endaxue/workspace/profile/node_modules/imager/lib/imager.js:122:18)
    at /Users/endaxue/workspace/profile/node_modules/imager/node_modules/async/lib/async.js:111:13
    at Array.forEach (native)
    at _each (/Users/endaxue/workspace/profile/node_modules/imager/node_modules/async/lib/async.js:32:24)
    at Object.async.each (/Users/endaxue/workspace/profile/node_modules/imager/node_modules/async/lib/async.js:110:9)
    at /Users/endaxue/workspace/profile/node_modules/imager/lib/imager.js:134:13
    at /Users/endaxue/workspace/profile/node_modules/imager/node_modules/async/lib/async.js:232:13
    at /Users/endaxue/workspace/profile/node_modules/imager/node_modules/async/lib/async.js:119:25
    at /Users/endaxue/workspace/profile/node_modules/imager/node_modules/async/lib/async.js:24:16

**Comment by xueenda** [comment]
/node_modules/imager/lib/imager.js
line 834 change to 
type: typeof(file) == 'string' ? mime.lookup(file) : file.type || file.mimetype,

will fix the problem
